name: CI/CD with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: priyanka1610
          password: ${{ secrets.DOCKERHUB_TOKEN }} # Use your Docker Hub access token here

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: priyanka1610/ci-cd-demo:latest

      - name: Verify Image
        run: docker pull priyanka1610/ci-cd-demo:latest
