name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: priyanka1610
          password: dckr_pat_JwuwIQEzJHwJOLhnmpi_ZZLkJd4

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: priyanka1610/ci-cd-demo:latest

      - name: Verify Image
        run: docker pull priyanka1610/ci-cd-demo:latest

